### ISSUE TITLE
Events - ACF Fields

### ISSUE THREAD

**Issue by baerkins** [bluecadet/greene-space#5]
- [x] Standard Tribe Fields
- [x] Content `WYSIWYG`
- [x] Duration `Text (or select?)`
- [x] Live Feed URL or ID `Text`
- [x] Live Video Date `Date`
- [ ] Ticketing Note (CONFIRM) `Text Area`
- [x] Ovation Performance ID (for API - sets up link and gets status) `Text`
- [x] Production Partners (Content) `Text Area`
- [x] Is Private `Bool`
- [ ] Sponsors (NEED TYPES) `TBD`

**TBD**
- [ ] Host `Taxonomy` or `Post Object`
- [ ] Guest `Taxonomy` or `Post Object`

**Comment by tylerjordanp724** [comment]
@baerkins I just added the majority of these fields. I left out the ones that are either TBD or need confirmation.
